import urllib.request
import re
import os

# Unicode sources
UNICODE_DATA_URL = "https://www.unicode.org/Public/15.1.0/ucd/UnicodeData.txt"
EMOJI_DATA_URL = "https://www.unicode.org/Public/15.1.0/ucd/emoji/emoji-data.txt"

# Property flags (must match your C enum)
U_PROP_LETTER = 1 << 0
U_PROP_EXTEND = 1 << 1
U_PROP_ZWJ = 1 << 2
U_PROP_EMOJI = 1 << 3
U_PROP_RI = 1 << 4
U_PROP_SYMBOL = 1 << 5

MAX_CP = 0x110000
props = [0] * MAX_CP

def fetch(url):
    print(f"Fetching {url}...")
    try:
        return urllib.request.urlopen(url).read().decode("utf-8")
    except Exception as e:
        print(f"Error fetching {url}: {e}")
        return ""

# --- Parse UnicodeData.txt ---
data = fetch(UNICODE_DATA_URL)
if data:
    for line in data.splitlines():
        if not line.strip(): continue
        fields = line.split(";")
        cp = int(fields[0], 16)
        category = fields[2]

        if category.startswith("L"):
            props[cp] |= U_PROP_LETTER
        elif category.startswith("M"):
            props[cp] |= U_PROP_EXTEND
        elif category.startswith("S"):
            props[cp] |= U_PROP_SYMBOL

# --- Parse emoji-data.txt ---
emoji_data = fetch(EMOJI_DATA_URL)
if emoji_data:
    for line in emoji_data.splitlines():
        if line.startswith("#") or not line.strip():
            continue

        match = re.match(r"([0-9A-F.]+)\s*;\s*(\w+)", line)
        if not match:
            continue

        rng, prop = match.groups()

        if ".." in rng:
            start, end = map(lambda x: int(x, 16), rng.split(".."))
        else:
            start = end = int(rng, 16)

        for cp in range(start, end + 1):
            if prop == "Emoji":
                props[cp] |= U_PROP_EMOJI
            if prop == "Regional_Indicator":
                props[cp] |= U_PROP_RI

# ZWJ explicitly
props[0x200D] |= U_PROP_ZWJ

# --- Compress into pages ---
print("Compressing tables...")

pages = {}
page_index = []
page_data = []

for high in range(MAX_CP >> 8):
    page = tuple(props[(high << 8):(high << 8) + 256])
    if page not in pages:
        pages[page] = len(page_data)
        page_data.append(page)
    page_index.append(pages[page])

# --- Emit C ---
output_path = "include/unicode_props.h"
print(f"Writing {output_path}")

with open(output_path, "w") as f:
    f.write("/**\n * GENERATED BY build_unicode_tables.py\n * O(1) Unicode property lookups via paged tables.\n */\n")
    f.write("#pragma once\n#include <stdint.h>\n\n")

    f.write("// Property flags\n")
    f.write(f"#define U_PROP_LETTER  {U_PROP_LETTER}\n")
    f.write(f"#define U_PROP_EXTEND  {U_PROP_EXTEND}\n")
    f.write(f"#define U_PROP_ZWJ     {U_PROP_ZWJ}\n")
    f.write(f"#define U_PROP_EMOJI   {U_PROP_EMOJI}\n")
    f.write(f"#define U_PROP_RI      {U_PROP_RI}\n")
    f.write(f"#define U_PROP_SYMBOL  {U_PROP_SYMBOL}\n\n")

    f.write(f"static const uint16_t unicode_page_index[{len(page_index)}] = {{\n    ")
    for i, idx in enumerate(page_index):
        f.write(f"{idx},")
        if (i + 1) % 16 == 0:
            f.write("\n    ")
    f.write("\n};\n\n")

    f.write(f"static const uint8_t unicode_props[{len(page_data)}][256] = {{\n")

    for page in page_data:
        f.write("    {")
        # Use short format for pages to keep file size reasonable
        f.write(",".join(map(str, page)))
        f.write("},\n")

    f.write("};\n")

    f.write("\nstatic inline uint8_t uprop(uint32_t cp) {\n")
    f.write("    if (cp >= 0x110000) return 0;\n")
    f.write("    uint16_t page = unicode_page_index[cp >> 8];\n")
    f.write("    return unicode_props[page][cp & 0xFF];\n")
    f.write("}\n")
